# Generated by Django 4.2.30 on 2026-06-06 01:32

from django.db import migrations, models


def create_initial_services(apps, schema_editor):
    service = apps.get_model("dao", "Service")
    initial_services = [
        {
            "name": "Móvil",
            "description": "Atención para líneas y servicios móviles.",
        },
        {
            "name": "Hogar",
            "description": "Atención para internet, telefonía y televisión del hogar.",
        },
        {
            "name": "Empresa",
            "description": "Atención y soporte para servicios empresariales.",
        },
    ]

    for item in initial_services:
        service.objects.get_or_create(name=item["name"], defaults=item)


def remove_initial_services(apps, schema_editor):
    service = apps.get_model("dao", "Service")
    service.objects.filter(name__in=["Móvil", "Hogar", "Empresa"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(db_column='servicio_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=250, null=True)),
                ('active', models.BooleanField(db_column='activo', default=True)),
            ],
            options={
                'db_table': 'servicios',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(create_initial_services, remove_initial_services),
    ]
