# Generated by Django 4.2.30 on 2026-06-06 01:57

from django.db import migrations, models
from django.contrib.auth.hashers import make_password
import django.db.models.deletion
import uuid


def create_demo_users(apps, schema_editor):
    user = apps.get_model("dao", "User")
    demo_users = [
        ("cliente.persona@demo.com", "Cliente Persona", "CLIENT_PERSON"),
        ("cliente.empresa@demo.com", "Cliente Empresa", "CLIENT_COMPANY"),
        ("asesor@demo.com", "Asesor de Atención", "OPERATOR"),
        ("supervisor@demo.com", "Supervisor de Atención", "SUPERVISOR"),
        ("admin@demo.com", "Administrador del Sistema", "ADMIN"),
    ]

    for username, full_name, role in demo_users:
        user.objects.update_or_create(
            username=username,
            defaults={
                "full_name": full_name,
                "role": role,
                "hashed_password": make_password("1234"),
            },
        )


def remove_demo_users(apps, schema_editor):
    user = apps.get_model("dao", "User")
    user.objects.filter(
        username__in=[
            "cliente.persona@demo.com",
            "cliente.empresa@demo.com",
            "asesor@demo.com",
            "supervisor@demo.com",
            "admin@demo.com",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT_PERSON', 'Client person'), ('CLIENT_COMPANY', 'Client company'), ('OPERATOR', 'Operator'), ('SUPERVISOR', 'Supervisor')], default='OPERATOR', max_length=50),
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=200, unique=True)),
                ('remember_me', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to='dao.user')),
            ],
            options={
                'db_table': 'sesiones_usuario',
                'indexes': [models.Index(fields=['token'], name='auth_session_token_idx'), models.Index(fields=['user', 'active'], name='auth_session_user_idx')],
            },
        ),
        migrations.RunPython(create_demo_users, remove_demo_users),
    ]
