# Generated by Django 4.2.30 on 2026-06-12 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0003_alter_user_role_authsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorNotification',
            fields=[
                ('id', models.BigAutoField(db_column='notificacion_id', primary_key=True, serialize=False)),
                ('notification_type', models.CharField(db_column='tipo', max_length=50)),
                ('channel', models.CharField(db_column='canal_envio', default='SISTEMA', max_length=40)),
                ('title', models.CharField(db_column='titulo', max_length=220)),
                ('message', models.TextField(db_column='mensaje')),
                ('priority', models.CharField(db_column='prioridad', default='media', max_length=20)),
                ('read', models.BooleanField(db_column='leida', default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_column='fecha_generacion')),
                ('read_at', models.DateTimeField(blank=True, db_column='fecha_lectura', null=True)),
                ('delivery_status', models.CharField(db_column='estado_envio', default='GENERADO', max_length=30)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['read', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='area_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=120, unique=True)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=250, null=True)),
                ('active', models.BooleanField(db_column='activo', default=True)),
            ],
            options={
                'db_table': 'areas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(db_column='caso_id', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='codigo_caso', max_length=40, unique=True)),
                ('case_type', models.CharField(choices=[('RECLAMO', 'Reclamo'), ('INCIDENCIA', 'Incidencia'), ('CONSULTA', 'Consulta'), ('SOLICITUD', 'Solicitud')], db_column='tipo_caso', max_length=20)),
                ('channel', models.CharField(db_column='canal_ingreso', max_length=60)),
                ('title', models.CharField(db_column='titulo', max_length=220)),
                ('description', models.TextField(db_column='descripcion')),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('response_due_at', models.DateTimeField(blank=True, db_column='fecha_limite_respuesta', null=True)),
                ('resolution_due_at', models.DateTimeField(blank=True, db_column='fecha_limite_resolucion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_ultima_actualizacion')),
                ('closed_at', models.DateTimeField(blank=True, db_column='fecha_cierre', null=True)),
                ('final_solution', models.TextField(blank=True, db_column='solucion_final', null=True)),
                ('pending_customer', models.BooleanField(db_column='pendiente_cliente', default=False)),
            ],
            options={
                'db_table': 'casos',
                'ordering': ['resolution_due_at', '-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAssignment',
            fields=[
                ('id', models.BigAutoField(db_column='asignacion_id', primary_key=True, serialize=False)),
                ('movement_type', models.CharField(db_column='tipo_movimiento', max_length=40)),
                ('reason', models.TextField(db_column='motivo')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_column='fecha_asignacion')),
            ],
            options={
                'db_table': 'asignaciones_caso',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.AutoField(db_column='categoria_id', primary_key=True, serialize=False)),
                ('case_type', models.CharField(choices=[('RECLAMO', 'Reclamo'), ('INCIDENCIA', 'Incidencia'), ('CONSULTA', 'Consulta'), ('SOLICITUD', 'Solicitud')], db_column='tipo_caso', max_length=20)),
                ('name', models.CharField(db_column='nombre', max_length=120)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=250, null=True)),
                ('active', models.BooleanField(db_column='activo', default=True)),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ['case_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CasePriority',
            fields=[
                ('id', models.AutoField(db_column='prioridad_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=60, unique=True)),
                ('level', models.PositiveSmallIntegerField(db_column='nivel')),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=250, null=True)),
                ('target_hours', models.PositiveIntegerField(db_column='tiempo_objetivo_horas', default=24)),
                ('active', models.BooleanField(db_column='activo', default=True)),
            ],
            options={
                'db_table': 'prioridades',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(db_column='estado_caso_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=250, null=True)),
                ('final', models.BooleanField(db_column='es_final', default=False)),
                ('visible_customer', models.BooleanField(db_column='visible_cliente', default=True)),
                ('order', models.PositiveSmallIntegerField(db_column='orden', default=1)),
                ('active', models.BooleanField(db_column='activo', default=True)),
            ],
            options={
                'db_table': 'estados_caso',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResponseTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_column='plantilla_id', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='codigo', max_length=40, unique=True)),
                ('name', models.CharField(db_column='nombre', max_length=160)),
                ('category', models.CharField(db_column='categoria', max_length=60)),
                ('channel', models.CharField(db_column='canal', max_length=100)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=250, null=True)),
                ('body', models.TextField(db_column='contenido')),
                ('active', models.BooleanField(db_column='activo', default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='creado_por_usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_templates', to='dao.user')),
            ],
            options={
                'db_table': 'plantillas_respuesta',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(db_column='cliente_id', primary_key=True, serialize=False)),
                ('customer_type', models.CharField(choices=[('PERSONA', 'Persona'), ('EMPRESA', 'Empresa')], db_column='tipo_cliente', max_length=20)),
                ('first_name', models.CharField(blank=True, db_column='nombres', max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, db_column='apellidos', max_length=120, null=True)),
                ('business_name', models.CharField(blank=True, db_column='razon_social', max_length=200, null=True)),
                ('document_type', models.CharField(db_column='documento_tipo', max_length=20)),
                ('document_number', models.CharField(db_column='documento_numero', max_length=30, unique=True)),
                ('email', models.EmailField(db_column='correo', max_length=200)),
                ('phone', models.CharField(blank=True, db_column='telefono', max_length=30, null=True)),
                ('address', models.CharField(blank=True, db_column='direccion', max_length=250, null=True)),
                ('active', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('user', models.OneToOneField(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to='dao.user')),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['document_number'],
            },
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.BigAutoField(db_column='historial_id', primary_key=True, serialize=False)),
                ('action', models.CharField(db_column='accion', max_length=80)),
                ('summary', models.CharField(blank=True, db_column='resumen', max_length=220, null=True)),
                ('observation', models.TextField(db_column='observacion')),
                ('visible_customer', models.BooleanField(db_column='es_visible_cliente', default=True)),
                ('event_at', models.DateTimeField(auto_now_add=True, db_column='fecha_evento')),
                ('case', models.ForeignKey(db_column='caso_id', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dao.case')),
                ('new_status', models.ForeignKey(blank=True, db_column='estado_nuevo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_as_new', to='dao.casestatus')),
                ('previous_status', models.ForeignKey(blank=True, db_column='estado_anterior_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_as_previous', to='dao.casestatus')),
                ('user', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_history_entries', to='dao.user')),
            ],
            options={
                'db_table': 'historial_caso',
                'ordering': ['-event_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvidence',
            fields=[
                ('id', models.BigAutoField(db_column='evidencia_id', primary_key=True, serialize=False)),
                ('file_name', models.CharField(db_column='nombre_archivo', max_length=250)),
                ('file_path', models.CharField(db_column='ruta_archivo', max_length=500)),
                ('mime_type', models.CharField(db_column='tipo_mime', max_length=150)),
                ('size_bytes', models.PositiveBigIntegerField(db_column='tamano_bytes', default=0)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=300, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='fecha_carga')),
                ('case', models.ForeignKey(db_column='caso_id', on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='dao.case')),
                ('history', models.ForeignKey(blank=True, db_column='historial_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='dao.casehistory')),
                ('user', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_evidence', to='dao.user')),
            ],
            options={
                'db_table': 'evidencias',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseCommunication',
            fields=[
                ('id', models.BigAutoField(db_column='comunicacion_id', primary_key=True, serialize=False)),
                ('communication_type', models.CharField(choices=[('SOLICITUD_INFORMACION', 'Solicitud de informacion'), ('RECORDATORIO_SLA', 'Recordatorio SLA'), ('RESPUESTA_PLANTILLA', 'Respuesta con plantilla')], db_column='tipo', max_length=40)),
                ('channel', models.CharField(db_column='canal_envio', max_length=60)),
                ('subject', models.CharField(db_column='asunto', max_length=220)),
                ('message', models.TextField(db_column='mensaje')),
                ('deadline_at', models.DateTimeField(blank=True, db_column='fecha_limite', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_column='fecha_envio')),
                ('case', models.ForeignKey(db_column='caso_id', on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='dao.case')),
                ('user', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_communications', to='dao.user')),
            ],
            options={
                'db_table': 'comunicaciones_caso',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='casecategory',
            constraint=models.UniqueConstraint(fields=('case_type', 'name'), name='unique_case_category'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, db_column='asignado_por_usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assignments_created', to='dao.user'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='case',
            field=models.ForeignKey(db_column='caso_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dao.case'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='destination_area',
            field=models.ForeignKey(blank=True, db_column='area_destino_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assignments_received', to='dao.area'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='destination_user',
            field=models.ForeignKey(blank=True, db_column='usuario_destino_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assignments_received', to='dao.user'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='source_area',
            field=models.ForeignKey(blank=True, db_column='area_origen_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assignments_sent', to='dao.area'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='source_user',
            field=models.ForeignKey(blank=True, db_column='usuario_origen_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assignments_sent', to='dao.user'),
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='dao.casecategory'),
        ),
        migrations.AddField(
            model_name='case',
            name='closed_by',
            field=models.ForeignKey(blank=True, db_column='cerrado_por_usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cases', to='dao.user'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='creado_por_usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to='dao.user'),
        ),
        migrations.AddField(
            model_name='case',
            name='current_area',
            field=models.ForeignKey(blank=True, db_column='area_actual_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_cases', to='dao.area'),
        ),
        migrations.AddField(
            model_name='case',
            name='customer',
            field=models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='dao.customer'),
        ),
        migrations.AddField(
            model_name='case',
            name='priority',
            field=models.ForeignKey(db_column='prioridad_id', on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='dao.casepriority'),
        ),
        migrations.AddField(
            model_name='case',
            name='responsible',
            field=models.ForeignKey(blank=True, db_column='responsable_actual_usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='dao.user'),
        ),
        migrations.AddField(
            model_name='case',
            name='service',
            field=models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='dao.service'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.ForeignKey(db_column='estado_caso_id', on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='dao.casestatus'),
        ),
        migrations.AddField(
            model_name='advisornotification',
            name='case',
            field=models.ForeignKey(blank=True, db_column='caso_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dao.case'),
        ),
        migrations.AddField(
            model_name='advisornotification',
            name='user',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dao.user'),
        ),
        migrations.AddIndex(
            model_name='casehistory',
            index=models.Index(fields=['case', 'event_at'], name='case_history_date_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['responsible', 'status'], name='case_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['resolution_due_at'], name='case_resolution_due_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['code'], name='case_code_idx'),
        ),
        migrations.AddIndex(
            model_name='advisornotification',
            index=models.Index(fields=['user', 'read'], name='notification_user_read_idx'),
        ),
    ]
